name: test
on: workflow_dispatch
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: run shell commands
        run: |
          echo "Hello, World! buiding code..."
  testing:
    runs-on: ubuntu-latest
    needs: building
    steps:
      - name: run shell commands
        run: |
          echo "Hello, World! testing code..."
  deploying:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: run shell commands
        run: |
          echo "Hello, World! deploying code..." 
        